# Site settings
title: "HokkienLang"
description: "泉漳話・福建話・台灣話"
author: "ZD"
email: your@email.com

# Logo & cover image
logo: "/assets/images/HokkienLang_blog_logo.png"
float_logo: true
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
author_image: "/assets/images/author.jpg"

paginate: 5

# GitHub Pages settings
url: "https://thehokkienlang.github.io"
baseurl: ""
