markdown: kramdown

# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "HokkienLang"
description: "泉漳話・福建話・台灣話"
author: "ZD"
email: your@email.com

# Logo & cover image
logo: "/assets/images/HokkienLang_blog_logo.png"
float_logo: true
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
author_image: "/assets/images/author.jpg"

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Dirk Fabisch'
author: 'Dirk Fabisch'
author_image: "/assets/images/author.jpg"

paginate:	5

# GitHub Pages settings
url: "https://thehokkienlang.github.io"
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
