# Site settings
title: "Hokkien Hangul"
description: "泉漳話・福建話・台灣話"
author: "ZD"
email: your@email.com

# Logo & cover image
logo: "/assets/images/df_logo.jpg"
float_logo: true
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"
author_image: "/assets/images/author.jpg"

paginate: 5

# GitHub Pages settings
url: "https://hokkien-lang.github.io"
baseurl: ""

# Social (optional)
social:
  - icon: github
    url: https://github.com/hokkien-lang
    desc: Fork me on GitHub
